### ISSUE TITLE
tensorflow 2

### ISSUE THREAD

**Issue by david-ngo-sixense** [dahliau/DPDist#4]
Hi @dahliau ,
Thanks for your work. It is very interesting.
Do you plan to re-implement your code using tensorflow 2?
I found it difficult to reproduce your work. Thanks very much.

**Comment by dahliau** [comment]
Hi @david-ngo-sixense ,
Currently there is no plan to re-implement the entire code. Is there a specific part which you found more difficult to re-implement? If so, let me know.
