### ISSUE TITLE
DPDist Model Trained

### ISSUE THREAD

**Issue by JuanRicardo444** [dahliau/DPDist#5]
Hello, I am very interested in your work and your great contribution. But I have a question regarding the code. To run it, do I have to train the DPDist model? or do you provide a file with the DPDist model already trained?

**Comment by dahliau** [comment]
Hey, tnx for your interest in our work.
About model weights, we do not provide pre-trained weights, but we provide the data we train with and our default training parameters which results in the published performances (it takes around 2-3 hours training, depends on your hardware, then you will have the weights for any further need).
