### ISSUE TITLE
train with ply data or kinect data

### ISSUE THREAD

**Issue by SabraHashemi** [dahliau/DPDist#6]
According to your documents you used the point cloud from cad software, 
I want to use .ply files to train model,
is that possible?

**Comment by dahliau** [comment]
Eventually, I used pre-sampled points from some CAD as you said. It doesn't matter if you will sample from other kinds of meshes. But you do need a very dense sampling to generate the training GT.
In `dataset_sample_with_gt.generate_points_with_gt` you can find the file where I read the points from. You can try copying the txt files structure or just modifying these rows.
