### ISSUE TITLE
Tests with Pointclouds > 3 000 000 Points

### ISSUE THREAD

**Issue by BestVanRome** [dahliau/DPDist#7]
Hi and shalom @dahliau  ;-),

thank you for your work. It looks very promising for my case.
I want to compare to "big" clouds together.

Have you ever tried your Application for those dimensions?
Can you estimate from your experience: will it be possible?

Best regards
Roman

**Comment by dahliau** [comment]
Hey Roman,
Well, this code is not suitable for more than ~2k points in each PC.
Theoretically, there is no upper barrier to the inputs for this method.

I didn't follow the latest progress in the field of "input size" to implicit neural functions, but I guess there are some new works related to this issue from the last two years.

**Comment by BestVanRome** [comment]
Thanks for the insights.
Good Luck
